boot.o: boot.S multiboot.h x86_desc.h types.h
handler_wrap.o: handler_wrap.S handler_wrap.h
x86_desc.o: x86_desc.S x86_desc.h types.h
functions.o: functions.c functions.h types.h i8259.h lib.h
i8259.o: i8259.c i8259.h types.h lib.h
idt.o: idt.c idt.h x86_desc.h types.h functions.h i8259.h lib.h \
  handler_wrap.h
kernel.o: kernel.c multiboot.h types.h x86_desc.h lib.h i8259.h debug.h \
  tests.h idt.h functions.h
lib.o: lib.c lib.h types.h
rtc.o: rtc.c rtc.h lib.h types.h i8259.h
tests.o: tests.c tests.h x86_desc.h types.h lib.h
