boot.o: boot.S multiboot.h x86_desc.h types.h
handler_wrap.o: handler_wrap.S handler_wrap.h
syscall_wrap.o: syscall_wrap.S x86_desc.h types.h
x86_desc.o: x86_desc.S x86_desc.h types.h
fs.o: fs.c fs.h types.h lib.h
functions.o: functions.c functions.h types.h i8259.h lib.h term.h fs.h \
  paging.h pcb.h x86_desc.h
i8259.o: i8259.c i8259.h types.h lib.h
idt.o: idt.c idt.h x86_desc.h types.h functions.h i8259.h lib.h \
  handler_wrap.h rtc.h syscall.h
kernel.o: kernel.c multiboot.h types.h x86_desc.h lib.h i8259.h debug.h \
  tests.h idt.h functions.h rtc.h paging.h term.h fs.h syscall.h
lib.o: lib.c lib.h types.h
paging.o: paging.c types.h x86_desc.h lib.h paging.h
pcb.o: pcb.c pcb.h types.h fs.h lib.h x86_desc.h
rtc.o: rtc.c rtc.h lib.h types.h i8259.h
syscall.o: syscall.c syscall.h types.h functions.h i8259.h lib.h term.h \
  fs.h paging.h pcb.h x86_desc.h
term.o: term.c term.h types.h functions.h i8259.h lib.h
tests.o: tests.c tests.h x86_desc.h types.h lib.h rtc.h term.h \
  functions.h i8259.h fs.h syscall.h
